from fastapi import FastAPI


SERVER_HOST = "0.0.0.0"
SERVER_PORT = 5002

DB_SERVER_HOST = "localhost"
DB_SERVER_PORT = 5001
DB_SERVER_URL = f"http://{DB_SERVER_HOST}:{DB_SERVER_PORT}"

RPI_SERVER_HOST = "192.168.100.17"
RPI_SERVER_PORT = 5005
RPI_SERVER_URL = f"http://{RPI_SERVER_HOST}:{RPI_SERVER_PORT}"

app = FastAPI()
